runtime: nodejs20
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
env_variables:
  PICARTA_API_TOKEN: 'UT44H8NQ8SD67Z60UOGS'
  EXPRESS_PORT: '8080'
  