version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/**/*
    - data/**/*
    - .platform/**/*
    - package.json
    - .ebextensions/**/* # AWS Elastic Beanstalk configuration files
    - .puppeteerrc.cjs
    - .npmrc
  discard-paths: no
