version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build
      - node node_modules/puppeteer/install.js

artifacts:
  files:
    - dist/**/*
    - data/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
    - ".ebextensions/**/*" # AWS Elastic Beanstalk configuration files
  discard-paths: no
