version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
    - ".ebextensions/**/*" # AWS Elastic Beanstalk configuration files
  discard-paths: no
